AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/**/*
    - bin/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/initializers/*
    - config/puma.rb

Documentation:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/LineLength:
  IgnoredPatterns: ['(\A|\s)#']

Style/FrozenStringLiteralComment:
  Enabled: false
